[package]
name = "drive-proof-verifier"
version = "1.0.0-pr.1694.8"
edition = "2021"
rust-version = "1.76"

crate-type = ["cdylib"]

[features]
default = ["mocks", "json"]
mocks = ["dep:serde"]
json = ["dep:serde_json"]


[dependencies]

thiserror = { version = "1.0.39" }
dapi-grpc = { path = "../dapi-grpc" }
drive = { path = "../rs-drive", default-features = false, features = [
    "verify",
] }
dpp = { path = "../rs-dpp" }
tenderdash-abci = { git = "https://github.com/dashpay/rs-tenderdash-abci", rev = "47d4105a49a4a332d5578a91371333686c7c5b1a" }
tracing = { version = "0.1.37" }
serde = { version = "1.0.171", default-features = false, optional = true }
serde_json = { version = "1.0.103", features = [
    "preserve_order",
], optional = true }
hex = { version = "0.4.3" }
