[package]
name = "drive-proof-verifier"
version = "0.25.0-dev"
edition = "2021"
rust-version = "1.70"

crate-type = ["cdylib"]

[features]
default = ["mocks", "json"]
bindgen = ["uniffi/cli", "dep:camino"]
mocks = ["drive/mockall", "dep:mockall"]
json = ["dep:serde_json"]
uniffi = ["dep:uniffi"]

[dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs", optional = true }
thiserror = { version = "1.0.39" }
bytes = { version = "1.4.0" }
camino = { version = "1.1.4", optional = true }
mockall = { version = "0.11", optional = true }

dapi-grpc = { path = "../dapi-grpc" }
drive = { path = "../rs-drive", default-features = false, features = [
    "verify",
] }
dpp = { path = "../rs-dpp" }
tenderdash-abci = { git = "https://github.com/dashpay/rs-tenderdash-abci" }
# tenderdash-abci = { path = "../../../rs-tenderdash-abci/abci" }
tracing = { version = "0.1.37" }
serde = { version = "1.0.171", default-features = false }
serde_json = { version = "1.0.103", features = [
    "preserve_order",
], optional = true }
lazy_static = { version = "1.4.0" }
hex = { version = "0.4.3" }

[dev-dependencies]
tracing-subscriber = { version = "0.3.16" }
serde_json = { version = "1.0.103" }
derive_more = { version = "0.99.16" }
base64 = { version = "0.21.0" }
hex = { version = "0.4.3" }

drive-abci = { path = "../rs-drive-abci", default-features = false }
# Dependencies for examples
rs-dapi-client = { path = "../rs-dapi-client" }
tokio = { version = "1.32.0", features = ["macros"] }
dashcore-rpc = { git = "https://github.com/dashpay/rust-dashcore-rpc", tag = "v0.15.1" }

async-trait = { version = "0.1.73" }

[build-dependencies]

uniffi = { git = "https://github.com/mozilla/uniffi-rs", features = [
    "build",
], optional = true }
