[package]
name = "rs-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
dapi-grpc = { path = "../dapi-grpc", features = ["client"] }
rs-dapi-client = { path = "../rs-dapi-client" }
drive = { path = "../rs-drive", default-features = false, features = [
    "verify",
] }
dpp = { path = "../rs-dpp" }
drive-proof-verifier = { path = "../rs-drive-proof-verifier" }

thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["macros"] }
async-trait = { version = "0.1.73" }
http = { version = "0.2.9" }
ciborium = { git = "https://github.com/qrayven/ciborium", branch = "feat-ser-null-as-undefined" }
serde = { version = "1.0.152", default-features = false }
tracing = { version = "0.1.37" }

# dashcore-rpc is only needed for core rpc; TODO remove once we have correct core rpc impl
dashcore-rpc = { git = "https://github.com/dashpay/rust-dashcore-rpc", rev = "7840fe65fbdf4f083ff8632f6e7afac11a31ca63" }
# drive-abci is only needed for core rpc; TODO remove once we have correct core rpc impl
drive-abci = { path = "../rs-drive-abci", default-features = false }


[dev-dependencies]
base64 = { version = "0.21.0" }
tracing-subscriber = { version = "0.3.16" }
