[package]
name = "platform-serialization"
authors = ["Samuel Westrich <sam@dash.org>"]
description = "Bincode based serialization and deserialization"
version = "1.0.0-dev.4"
edition = "2021"
# Update using scripts/update-rust-toolchain.sh
rust-version = "1.76"
license = "MIT"
private = true

[dependencies]
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
platform-version = { path = "../rs-platform-version" }
