[package]
name = "rs-dapi-client"
version = "0.1.0"
edition = "2021"

[features]
default = ["mocks"]
mocks = [
    "dep:mockall",
    "dep:serde",
    "dep:serde_json",
    "dep:drive-proof-verifier",
    "dep:dpp",
    "dep:bincode",
]
platform_integration_tests = []


[dependencies]
backon = "0.4.1"
dapi-grpc = { path = "../dapi-grpc", features = ["client"] }
futures = "0.3.28"
http = "0.2.9"
rand = { version = "0.8.5", features = ["small_rng"] }
thiserror = "1.0.41"
tonic = "0.9.2"
tracing = "0.1.37"
mockall = { version = "0.11", optional = true }
serde = { version = "1.0.171", default-features = false, optional = true }
serde_json = { version = "1.0.103", features = [
    "preserve_order",
], optional = true }
drive-proof-verifier = { path = "../rs-drive-proof-verifier", features = [
    "mocks",
], optional = true }
bincode = { version = "2.0.0-rc.3", features = ["serde"], optional = true }
tokio = { version = "1.32.0", default-features = false }

# FIXME: we don't need all features, but it doesn't build when we limit it
dpp = { path = "../rs-dpp", default-features = false, optional = true }

[dev-dependencies]
tokio = { version = "1.32.0", features = ["macros"] }
