---
name: "Setup Node.JS"
description: "Setup Node.JS binaries, dependencies and cache"
runs:
  using: composite
  steps:
    - name: Setup Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Enable corepack
      shell: bash
      run: corepack enable

    - name: Disable NPM audit
      shell: bash
      run: npm config set audit false

    - name: Cache NPM build artifacts (S3 bucket cache)
      uses: strophy/actions-cache@opendal-update
      if: contains(runner.name, 'ubuntu-platform')
      with:
        bucket: multi-runner-linux-x64-platform-cache-ui535z23
        root: actions-cache
        path: |
          .yarn/unplugged
        key: ${{ runner.os }}/yarn/unplugged/${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}/yarn/unplugged/

    - name: Cache NPM build artifacts (GitHub Actions cache)
      uses: actions/cache@v3
      if: ${{ !contains(runner.name, 'ubuntu-platform') }}
      with:
        path: |
          .yarn/unplugged
        key: ${{ runner.os }}-yarn-unplugged-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-unplugged-

    - name: Install dependencies
      shell: bash
      run: yarn install
