'@dashevo/dapi-grpc':
  - .github/workflows/js-checks.yml
  - packages/dapi-grpc/**
  - packages/js-grpc-common/**

'@dashevo/dapi':
  - .github/workflows/js-checks.yml
  - packages/dapi/**
  - packages/dapi-grpc/**
  - packages/rs-dpp/**
  - packages/wasm-dpp/**
  - packages/js-grpc-common/**
  - packages/js-dapi-client/**
  - packages/dashpay-contract/**
  - packages/feature-flags-contract/**
  - packages/dpns-contract/**
  - packages/masternode-reward-shares-contract/**
  - packages/dash-spv/**

'@dashevo/dash-spv':
  - .github/workflows/js-checks.yml
  - packages/dash-spv/**

dashmate:
  - .github/workflows/js-checks.yml
  - packages/dashmate/**
  - packages/js-dash-sdk/**
  - packages/wallet-lib/**
  - packages/js-dapi-client/**
  - packages/dapi-grpc/**
  - packages/wasm-dpp/**
  - packages/rs-dpp/**
  - packages/js-grpc-common/**
  - packages/dashpay-contract/**
  - packages/feature-flags-contract/**
  - packages/masternode-reward-shares-contract/**
  - packages/dpns-contract/**
  - packages/dash-spv/**

'@dashevo/dashpay-contract':
  - .github/workflows/js-checks.yml
  - packages/dashpay-contract/**
  - packages/wasm-dpp/**
  - packages/rs-dpp/**
  - packages/feature-flags-contract/**
  - packages/dpns-contract/**

'@dashevo/dapi-client':
  - .github/workflows/js-checks.yml
  - packages/js-dapi-client/**
  - packages/dapi-grpc/**
  - packages/js-grpc-common/**
  - packages/dashpay-contract/**
  - packages/feature-flags-contract/**
  - packages/dpns-contract/**
  - packages/masternode-reward-shares-contract/**
  - packages/dash-spv/**

dash:
  - .github/workflows/js-checks.yml
  - packages/js-dash-sdk/**
  - packages/wallet-lib/**
  - packages/js-dapi-client/**
  - packages/dapi-grpc/**
  - packages/js-grpc-common/**
  - packages/dashpay-contract/**
  - packages/feature-flags-contract/**
  - packages/masternode-reward-shares-contract/**
  - packages/dpns-contract/**
  - packages/dash-spv/**

'@dashevo/grpc-common':
  - .github/workflows/js-checks.yml
  - packages/js-grpc-common/**

'@dashevo/platform-test-suite':
  - .github/workflows/js-checks.yml
  - packages/platform-test-suite/**
  - packages/js-dash-sdk/**
  - packages/wallet-lib/**
  - packages/js-dapi-client/**
  - packages/dapi-grpc/**
  - packages/js-grpc-common/**
  - packages/dashpay-contract/**
  - packages/feature-flags-contract/**
  - packages/masternode-reward-shares-contract/**
  - packages/dpns-contract/**
  - packages/dash-spv/**

'@dashevo/wallet-lib':
  - .github/workflows/js-checks.yml
  - packages/wallet-lib/**
  - packages/js-dapi-client/**
  - packages/dapi-grpc/**
  - packages/js-grpc-common/**
  - packages/dashpay-contract/**
  - packages/feature-flags-contract/**
  - packages/dpns-contract/**
  - packages/masternode-reward-shares-contract/**
  - packages/dash-spv/**

'@dashevo/wasm-dpp':
  - .github/workflows/js-checks.yml
  - packages/js-dpp/**
  - packages/feature-flags-contract/**
  - packages/masternode-reward-shares-contract/**
  - packages/dpns-contract/**
  - packages/dashpay-contract/**
  - packages/wasm-dpp/**
