on:
  workflow_call:
    inputs:
      command:
        description: Run tests command
        type: string
        default: test
        required: true

jobs:
  test-suite:
    name: Run Test Suite
    # TODO: Try with Github Runner, probably it will be the same time
    runs-on: [ "self-hosted", "linux", "x64", "ubuntu-platform" ]
    timeout-minutes: 120
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS credentials and bucket region
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Node.JS
        uses: ./.github/actions/nodejs

      - name: Restore JS build artifacts
        uses: strophy/actions-cache@opendal-update
        with:
          bucket: multi-runner-linux-x64-platform-cache-ui535z23
          root: actions-cache
          path: build-js-artifacts-${{ github.sha }}.tar
          key: ${{ runner.os }}/build-js-artifacts/${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}/build-js-artifacts/${{ github.sha }}

      - name: Unpack JS build artifacts archive
        run: tar -xf build-js-artifacts-${{ github.sha }}.tar

      - name: Setup local network
        run: |
          set -ex

          # create tenderdash blocks every 10s to speed up test suite
          yarn dashmate config set --config=local platform.drive.tenderdash.consensus.createEmptyBlocksInterval "10s"

          # collect drive logs for bench suite
          yarn dashmate config set --config=local platform.drive.abci.logs.stdout.level "trace"

          # Login to ECR
          DOCKER_HUB_ORG="${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin $DOCKER_HUB_ORG

          SHA_TAG=sha-${{ github.sha }}

          # Drive
          yarn dashmate config set --config=local platform.drive.abci.docker.image $DOCKER_HUB_ORG/drive:$SHA_TAG

          # DAPI
          yarn dashmate config set --config=local platform.dapi.api.docker.image $DOCKER_HUB_ORG/dapi:$SHA_TAG

          # Dashmate helper image is hardcoded so we replace it with the built one
          VERSION=$(cat package.json | jq -r '.version')
          docker pull $DOCKER_HUB_ORG/dashmate_helper:$SHA_TAG
          docker tag $DOCKER_HUB_ORG/dashmate_helper:$SHA_TAG dashpay/dashmate-helper:${VERSION}

          # TODO: Move setup network to a separate job before test suite to do not run twice?
          ./scripts/setup_local_network.sh
          ./scripts/configure_test_suite.sh
          ./scripts/configure_dotenv.sh
        shell: bash

      - name: Start local network
        run: yarn start

      # TODO: We running these tests twice
      - name: Run Wallet functional tests
        run: yarn workspace @dashevo/wallet-lib test:functional

      # TODO: We running these tests twice
      - name: Run SDK functional tests
        run: yarn workspace dash test:functional

      - name: Run test suite
        run: yarn workspace @dashevo/platform-test-suite ${{ inputs.command }}

      - name: Show Docker logs
        if: ${{ failure() }}
        uses: jwalton/gh-docker-logs@v2
