on:
  workflow_call:
    inputs:
      package:
        description: The package name to run tests for
        type: string
        required: true
      skip-tests:
        description: Skip running tests
        type: boolean
        default: false
        required: false
      test-command:
        description: Test command to run
        type: string
        default: test
        required: false

jobs:
  lint:
    name: Linting
    runs-on: [ "self-hosted", "linux", "x64", "ubuntu-platform" ]
    timeout-minutes: 15
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials and bucket region
        uses: aws-actions/configure-aws-credentials@v4
        if: contains(runner.name, 'ubuntu-platform')
        with:
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Node.JS
        uses: ./.github/actions/nodejs

      - name: Restore JS build artifacts
        uses: everpcpc/actions-cache@v1
        with:
          bucket: multi-runner-linux-x64-platform-cache-ui535z23
          root: actions-cache
          path: build-js-artifacts-${{ github.sha }}.tar
          key: ${{ runner.os }}/build-js-artifacts/${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}/build-js-artifacts/${{ github.sha }}

      - name: Unpack JS build artifacts archive
        run: tar -xf build-js-artifacts-${{ github.sha }}.tar

      - name: Run ESLinter
        run: yarn workspace "${{ inputs.package }}" lint

  test:
    name: Tests
    runs-on: [ "self-hosted", "linux", "x64", "ubuntu-platform" ]
    timeout-minutes: 120
    if: ${{ !inputs.skip-tests }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      - name: Configure AWS credentials and bucket region
        uses: aws-actions/configure-aws-credentials@v4
        if: contains(runner.name, 'ubuntu-platform')
        with:
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Node.JS
        uses: ./.github/actions/nodejs

      - name: Restore JS build artifacts
        uses: everpcpc/actions-cache@v1
        with:
          bucket: multi-runner-linux-x64-platform-cache-ui535z23
          root: actions-cache
          path: build-js-artifacts-${{ github.sha }}.tar
          key: ${{ runner.os }}/build-js-artifacts/${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}/build-js-artifacts/${{ github.sha }}

      - name: Unpack JS build artifacts archive
        run: tar -xf build-js-artifacts-${{ github.sha }}.tar

      - name: Create necessary dotenv files
        run: |
          cp packages/dapi/.env.example packages/dapi/.env

      # TODO: Use test-command input
      - name: Set test-command
        id: test-command
        uses: actions/github-script@v6
        with:
          script: |
            if (${{ inputs.package }} === '@dashevo/dashmate') {
              return 'test:unit';
            }
            return 'test';
          result-encoding: string

      - name: Run tests
        run: yarn workspace "${{ inputs.package }}" ${{ steps.test-command.outputs.result }}
