on:
  workflow_call:

jobs:
  build-js:
    name: Build JS
    runs-on: [ "self-hosted", "linux", "x64", "ubuntu-platform" ]
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Node.JS
        uses: ./.github/actions/nodejs

      - name: Setup Rust
        uses: ./.github/actions/rust
        with:
          target: wasm32-unknown-unknown

      # TODO: Use `yarn build` and store build artifacts so they are available in later runs

      - name: Build SDK
        run: yarn workspace @dashevo/wasm-dpp build
