on:
  workflow_call:
    inputs:
      test-pattern:
        type: string
        description: Test pattern. i.e. test/e2e/*.spec.js
        required: true

jobs:
  dashmate-test:
    name: Run Dashmate test
    # TODO: Try with Github Runner, probably it will be the same time
    runs-on: [ "self-hosted", "linux", "x64", "ubuntu-platform" ]
    timeout-minutes: 30
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS credentials and bucket region
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Node.JS
        uses: ./.github/actions/nodejs

      - name: Restore JS build artifacts
        uses: strophy/actions-cache@opendal-update
        with:
          bucket: multi-runner-linux-x64-platform-cache-ui535z23
          root: actions-cache
          path: build-js-artifacts-${{ github.sha }}.tar
          key: ${{ runner.os }}/build-js-artifacts/${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}/build-js-artifacts/${{ github.sha }}

      - name: Unpack JS build artifacts archive
        run: tar -xf build-js-artifacts-${{ github.sha }}.tar

      - name: Pull pre-built images
        run: |
          # Login to ECR
          DOCKER_HUB_ORG="${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin $DOCKER_HUB_ORG

          SHA_TAG=sha-$(git rev-parse --short HEAD)

          # Drive
          DRIVE_IMAGE_AND_VERSION=$(yarn dashmate config get --config=local platform.drive.abci.docker.image)
          docker pull $DOCKER_HUB_ORG/drive:$SHA_TAG
          docker tag $DOCKER_HUB_ORG/drive:$SHA_TAG $DRIVE_IMAGE_AND_VERSION

          # DAPI
          DAPI_IMAGE_AND_VERSION=$(yarn dashmate config get --config=local platform.dapi.api.docker.image)
          docker pull $DOCKER_HUB_ORG/dapi:$SHA_TAG
          docker tag $DOCKER_HUB_ORG/dapi:$SHA_TAG $DAPI_IMAGE_AND_VERSION

          # Dashmate helper image is hardcoded so we replace it with the built one
          VERSION=$(cat package.json | jq -r '.version')
          docker pull $DOCKER_HUB_ORG/dashmate_helper:$SHA_TAG
          docker tag $DOCKER_HUB_ORG/dashmate_helper:$SHA_TAG dashpay/dashmate-helper:${VERSION}
        shell: bash

      - name: Run tests
        run: yarn workspace dashmate run mocha ${{ inputs.test-pattern }}
        env:
          DASHMATE_E2E_TESTS_SKIP_BUILD: true

      - name: Show Docker logs
        if: ${{ failure() }}
        uses: jwalton/gh-docker-logs@v2

