on:
  workflow_call:
    inputs:
      command:
        description: Run tests command
        type: string
        default: test
        required: true

jobs:
  test-suite:
    name: Run Test Suite
    runs-on: [ "self-hosted", "linux", "x64", "ubuntu-platform" ]
    timeout-minutes: 120
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Node.JS
        uses: ./.github/actions/nodejs

      - name: Setup Rust
        uses: ./.github/actions/rust
        with:
          target: wasm32-unknown-unknown

      - name: Restore JS build artifacts
        uses: everpcpc/actions-cache@v1
        with:
          bucket: multi-runner-linux-x64-platform-cache-ui535z23
          root: actions-cache
          path: build-js-artifacts-${{ github.sha }}.tar
          key: ${{ runner.os }}-build-js-artifacts-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-js-artifacts-${{ github.sha }}

      - name: Unpack JS build artifacts archive
        run: tar -xf build-js-artifacts-${{ github.sha }}.tar

      - name: Setup local network
        run: |
          # create tenderdash blocks every 10s to speed up test suite
          yarn dashmate config set --config=local platform.drive.tenderdash.consensus.createEmptyBlocksInterval “10s”
          # collect drive logs for bench suite
          yarn dashmate config set --config=local platform.drive.abci.logs.stdout.level “trace”
          # set docker image names
          yarn dashmate config set --config=local platform.drive.abci.docker.image drive:${{ github.sha }}
          yarn dashmate config set --config=local platform.dapi.api.docker.image dapi:${{ github.sha }}
          yarn dashmate config set --config=local dashmate.helper.docker.image dashmate_helper:${{ github.sha }}

          source ./scripts/setup_local_network.sh
          source ./scripts/configure_test_suite.sh
          source ./scripts/configure_dotenv.sh
        shell: bash

      - name: Start local network
        run: yarn start

      - name: Run Wallet functional tests
        run: yarn workspace @dashevo/wallet-lib test:functional

      - name: Run SDK functional tests
        run: yarn workspace dash test:functional

      - name: Run test suite
        run: yarn workspace @dashevo/platform-test-suite ${{ inputs.command }}

      - name: Show Docker logs
        if: ${{ failure() }}
        uses: jwalton/gh-docker-logs@v2
