version: '3.7'

services:
  dapi_envoy_rate_limiter_metrics:
    image: ${PLATFORM_DAPI_ENVOY_RATE_LIMITER_METRICS_DOCKER_IMAGE:?err}
    labels:
      org.dashmate.service.title: "DAPI Envoy rate limiter metrics exporter"
    restart: unless-stopped
    entrypoint: /bin/statsd_exporter
    command:
      - "--statsd.mapping-config=/etc/statsd-exporter/config.yaml"
    networks:
      - envoy_rate_limiter
    volumes:
      - ${DASHMATE_HOME_DIR:?err}/${CONFIG_NAME:?err}/platform/dapi/envoy/rate_limiter/statsd_exporter.yaml:/etc/statsd-exporter/config.yaml:ro
    expose:
      - 9125
      - 9125/udp
    ports:
      - ${PLATFORM_DAPI_ENVOY_RATE_LIMITER_METRICS_HOST:?err}:${PLATFORM_DAPI_ENVOY_RATE_LIMITER_METRICS_PORT:?err}:9102
