version: '3.7'

services:
  drive_abci:
    build:
      context: ${PLATFORM_SOURCE_PATH:?err}
      dockerfile: ${PLATFORM_SOURCE_PATH:?err}/packages/rs-drive-abci/Dockerfile
      args:
        SCCACHE_MEMCACHED: ${SCCACHE_MEMCACHED}
        SCCACHE_GHA_ENABLED: ${SCCACHE_GHA_ENABLED}
        SCCACHE_BUCKET: ${SCCACHE_BUCKET}
        ACTIONS_CACHE_URL: ${ACTIONS_CACHE_URL}
        ACTIONS_RUNTIME_TOKEN: ${ACTIONS_RUNTIME_TOKEN}
      cache_from:
        - "type=s3,region=eu-west-1,bucket=platform-runner-cache,name=cache-image"
    image: drive:local
    stop_grace_period: 30s

  dapi_api:
    build:
      context: ${PLATFORM_SOURCE_PATH:?err}
      dockerfile: ${PLATFORM_SOURCE_PATH:?err}/packages/dapi/Dockerfile
    image: dapi:local
    stop_grace_period: 10s

  dapi_tx_filter_stream:
    build:
      context: ${PLATFORM_SOURCE_PATH:?err}
      dockerfile: ${PLATFORM_SOURCE_PATH:?err}/packages/dapi/Dockerfile
    image: dapi:local
    stop_grace_period: 10s

  dapi_envoy:
    build:
      context: ${PLATFORM_SOURCE_PATH:?err}
      dockerfile: ${PLATFORM_SOURCE_PATH:?err}/packages/dashmate/docker/envoy/Dockerfile
    image: dapi-envoy:local
    stop_grace_period: 10s

  dashmate_helper:
    build:
      context: ${PLATFORM_SOURCE_PATH:?err}
      dockerfile: ${PLATFORM_SOURCE_PATH:?err}/packages/dashmate/Dockerfile
    image: dashmate_helper:local
    stop_grace_period: 10s
