[package]
name = "platform-version"
authors = ["Samuel Westrich <sam@dash.org>"]
description = "Bincode based serialization and deserialization"
version = "1.0.0-dev.16"
edition = "2021"
rust-version = "1.76"
license = "MIT"

[dependencies]
thiserror = { version = "1.0.59" }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }

[features]
mock-versions = []
